server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: auth-service
          uri: https://github.com/facundoArambillet/Microservices
          search-paths: config-data
  application:
    name: config-service
